name: Duplicate Issue Detection

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  similarity:
    runs-on: ubuntu-latest
    if: "!github.event.issue.pull_request"
    steps:
      - name: Check issue similarity
        uses: actions-cool/issues-similarity@v1
        with:
          filter-threshold: 0.75
          title-threshold: 0.85
          comment: |
            Potential duplicate detected: #{number}.

            Check that issue to see if this has already been reported or resolved.
          close-issue: false
